name: C Windows Build with MinGW

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: windows-latest
      
    steps:
      # Using actions checkout v3 to copy repo to virtual system
      - name: Checkout repository
        uses: actions/checkout@v3
  
      # install mingw and pass to system path
      - name: Install MinGW
        run: |  
          choco install mingw
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH
          where gcc
          
      # install msys2 and add to system path
      - name: Install MSYS2
        run: |
          choco install msys2
          echo "C:\tools\msys64\mingw64\bin" >> $GITHUB_PATH
          
      - name: Check MSYS2
        run: |
          ls C:\tools\msys64\usr\bin
          ls C:\tools\msys64\mingw64\bin

      - name: Install SDL2 with Pacman
        run: |
            pacman -S mingw-w64-x86_64-SDL2 --noconfirm
            find /c/tools/msys64 -name "SDL.h"
            find /c/tools/msys64 -name "SDL_ttf.h"
            find /c/tools/msys64 -name "libSDL2.a"
            find /c/tools/msys64 -name "libSDL2_ttf.a"
          
      - name: Build with MinGW
        run: |
            mkdir -p $GITHUB_WORKSPACE/bin
            mingw32-make LIBRARY_DIR="-L C:/tools/msys64/mingw64/lib" INCLUDES=" -I $GITHUB_WORKSPACE/include -I C:/tools/msys64/mingw64/include/SDL2"
  
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
            name: compiled-binaries
            path: $GITHUB_WORKSPACE/bin/main


